version: '3.8'

services:
  # Aplicaci√≥n FESC
  app:
    build: .
    ports:
      - "${APP_PORT}:4321"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - ADMIN_ROLE=${ADMIN_ROLE}
    volumes:
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped